Tourest/config/routes.rb
Rails.application.routes.draw do

  resources :galleries
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' , registrations: 'registrations' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  root 'tourest#index'

  as :user do
    get '/users/sign_out' => 'devise/sessions#destroy'       
    put "users/:id" => "users#update"     
  end
  get 'new' => 'galleries#new'
  get 'index' =>  'tourest#index'
  get 'about' =>  'tourest#about'
  get 'contact' =>  'tourest#contact'

  get 'users/update'

  get 'users/finish_signup'

  resources "tourest"

  resources "users"
  
end

Tourest/app/models/gallery.rb
class Gallery < ActiveRecord::Base
	mount_uploader :file, PictureUploader
	
end

Tourest/app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:title, :description, :file)
    end
end

Tourest/app/helpers/galleries_helper.rb
module GalleriesHelper
end

Tourest/app/views/galleries/_form.html.erb
  <%= form_for @gallery, :html => {:multipart => true} do |f| %>
 <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="col-sm-offset-1 col-xs-10" id="hbg">
     <div class="collapse navbar-collapse" >
  <h4>
      <ul class="nav navbar-nav">

      <li> <%=link_to 'Photo Gallery', galleries_path, style: "color:#fff;" %></li>
        <!-- <li><%= link_to 'Add Photo', new_gallery_path %></li> -->
         
      </ul>
      </h4>
    </div>
    </h1>
  <div class="col-sm-offset-3 col-sm-6 col-xs-12"  style="margin-top:50px;" id="blocklogin">

          <form>

            <div class="title-log" style="color:Lavender">Log in</div>
            <div class="form-group" style="color:Lavender">
               <%= f.label :title , style:'margin-top: 10px;'%><br>
                <%= f.text_field :title, class:'form-control', style:'margin-top: 10px;'%>
             </div>
              
           
            <div class="form-group" style="color:Lavender;">
              <%= f.label :description, style:'margin-top: 30px;' %><br>
              <%= f.text_area :description, class:'form-control', style:'margin-top: 10px;' %>
            </div>
            
              <div  class="form-group" style="color:LightGoldenRodYellow;">
              <%= f.label :file , style:'margin-top: 30px;' %><br>
                <%= f.file_field :file , style:'margin-top: 10px;'%>
                
              </div>

            <div class="form-group col-sm-offset-5">
            
             <%= f.submit class:'btn btn-default', style:'margin-top: 30px;' %>

          </div>
          <div class="form-group" style="color:LightGoldenRodYellow;">
            
            
              <%= link_to 'Show', @gallery,  class:' btn btn-default' %> 
              <%= link_to 'Back', galleries_path,  class:'col-sm-offset-9 btn btn-default' %>

          </div>

         
          </form>
          </div>
          </div>
<% end %>

        
</div>

Tourest/app/views/galleries/edit.html.erb
<% provide(:title, "edit") %>
<%= render 'form' %>

Tourest/app/views/galleries/index.html.erb
<h4 style="margin-top:60px;"> 
        <%= link_to 'Add Photo', new_gallery_path %>         
</h4>

<% @galleries.in_groups_of(4) do |group| %>
  <div class="row" style="margin-top:50px;">
    <% group.compact.each do |photo| %>
      <div class="col-md-4 col-sm-12 col-xs-12">
      <center>
        <h4><%= link_to photo.title, photo, class:'text-main' %></h4></center>
        <%= link_to image_tag photo.file_url, :width => '100%',:height => '300px' if photo.file.present?%>
        
        <%= photo.description %>
        <div style="padding:10px;">
        <%=link_to 'More', photo %>
           <!--  <a href="" class="my-btn-cate">More</a> -->
      </div>
      </div>
    <% end %>
  </div>
<% end %>

Tourest/app/views/galleries/new.html.erb
<% provide(:title, "New") %>
 
<!-- <h1 style="margin-top:100px;">New Gallery</h1> -->

<%= render 'form' %>

Tourest/app/views/galleries/show.html.erb
<p id="notice" style="margin-top:100px;"><%= notice %></p>

<div class="row">
  <div class="col-xs-9">
    <%= image_tag(@gallery.file_url, :width => "100%") if @gallery.file.present? %>
  </div>

  <div class="col-xs-3">
    <h4  style="color:DeepSkyBlue"><b>Title&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: </b><%= @gallery.title%></h4>
    <h4 style="color:DeepSkyBlue"><b>Description: </b><%= @gallery.description %></h4>
    <p>
      <%= link_to 'Edit', edit_gallery_path(@gallery) %> |
      <%= link_to 'Delete', @gallery, confirm: 'Are you sure?', method: :delete %> |
      <%= link_to 'Back', galleries_path %>
    </p>
  </div>
</div>
 