Tourest/config/routes.rb
Rails.application.routes.draw do

  resources :galleries
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' , registrations: 'registrations' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  root 'tourest#index'

  as :user do
    get '/users/sign_out' => 'devise/sessions#destroy'       
    put "users/:id" => "users#update"     
  end
  get 'new' => 'galleries#new'
  get 'index' =>  'tourest#index'
  get 'about' =>  'tourest#about'
  get 'contact' =>  'tourest#contact'

  get 'users/update'

  get 'users/finish_signup'

  resources "tourest"

  resources "users"
  
end

Tourest/app/views/layouts/_footer.html.erb
<!-- ============================ start footer ========================================= -->
<div class="footer">
	<div class="container">
		<div class="col-sm-4 col-xs-12">
			<div class="title-list-foot">Information</div>
				<ul class="content-list-foot">
					<li>
						<a href="#">News & events</a>
					</li>
					<li>
						<a href="#">Gallery</a>
					</li>
					<li>
						<a href="#">Site Map</a>
					</li>
			
				</ul>
		</div>
		<div class="col-sm-4 col-xs-12">
			<div class="title-list-foot">Information</div>
			<ul class="content-list-foot">
				<li>
					<%= link_to "About Us",   about_path %>
				</li>
				<li>
					<%= link_to "Contact",   contact_path %>
				</li>
				<li>
					<a href="#">Register</a>
					
				</li>
				
			</ul>
		</div>
		<div class="col-sm-4 col-xs-12">
			<div class="title-list-foot">Information</div>	
			<ul class="content-list-foot">
				<li>
					<a href="www.facebook.com/" target="new"><img src="/assets/fb.png" width="20px">&nbsp;: Facebook</a>
					
				</li>
				<li>
					<a href="www.linkedin.com" target="new"><img src="/assets/linkedin.png" width="20px"/>&nbsp;: Linkedin</a>
				</li>
				<li>
					 <a href="www.twitter.com" target="new"><img src="/assets/twitter.png" width="20px" />&nbsp;: Twitter</a>
				</li>

			</ul>	
		</div>
	</div>
</div>
<div class="cp-right">
		<div class="container">Copyright © Tourest.com . All Rights Reserved.</div>
</div>

Tourest/app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse" id="mynav">
	<div class="container">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-col" aria-expanded="false" id="my-tog">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "Tourest", root_path, id: "mybrand", class: "navbar-brand" %>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="nav-col">
					
			<ul class="nav navbar-nav navbar-right" id="myul-r">
				<li>
					<a href="#">News & events</a>
				</li>
				<li>
					<%= link_to "Gallery", galleries_path %>
				</li>
				<li>
					<%= link_to "About Us",   about_path %>
				</li>
				<li>
					<%= link_to "Contact",   contacts_path %>
				</li>
				<li>
					<% if user_signed_in? && !current_user.blank? %>

						<%= link_to "Profile", current_user %>
						</li>
						<li>
						<%= link_to "Logout", destroy_user_session_path, :method => :deletee %>
						</li>

					<% else %>
						<%= link_to 'Log in', new_user_session_path %>

					<% end %>
				</li>
						
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>

Tourest/app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'layouts', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="/assets/bootstrap.css">
  <link rel="stylesheet" href="/assets/bootstrap-theme.css">
  <link rel="stylesheet" href="/assets/mystyle.css">
  <script src="/assets/jquery-2.1.4.js"></script>

  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Photo Gallery</a>
    </div>
     <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/photos">Photos</a></li>
        <li><%= link_to 'Add Photo', new_gallery_path %></li>
      </ul>
    </div>
  </div>
</nav>
  <%= render 'layouts/header' %>
  
  <div class="container">
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>

<script src="/assets/bootstrap.js"></script>
</body>
<footer>
  <div class="container">
    Rails Girls 2014
  </div>
</footer>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</body>
</html>