Tourest/config/routes.rb
Rails.application.routes.draw do

  resources :galleries
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' , registrations: 'registrations' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  root 'tourest#index'

  as :user do
    get '/users/sign_out' => 'devise/sessions#destroy'       
    put "users/:id" => "users#update"     
  end
  get 'new' => 'galleries#new'
  get 'index' =>  'tourest#index'
  get 'about' =>  'tourest#about'
  get 'contact' =>  'tourest#contact'

  get 'users/update'

  get 'users/finish_signup'

  resources "tourest"

  resources "users"
  
end

Tourest/app/models/user.rb
class User < ActiveRecord::Base
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable, :confirmable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  validates :name, presence: true
  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update
  
  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

Tourest/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy , :finish_signup]
  
  def index
    @user = User.all
    render json: {json_users:@user} # get json data as an object
  end
  # GET /users/:id.:format
  def show
    @user = User.find(params[:id])

    respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @user }
    end
  end

  # GET /users/:id/edit
  def edit
    # authorize! :update, @user
    @user = User.find(params[:id])
  end

  # PATCH/PUT /users/:id.:format
  def update
    # authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user 
    if request.patch? && params[:user] #&& params[:user][:email]
      if @user.update(user_params)
        @user.skip_reconfirmation!
        sign_in(@user, :bypass => true)
        redirect_to @user, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
  
  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      accessible = [ :name, :email ] # extend with your own params
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end
end

Tourest/app/helpers/users_helper.rb
module UsersHelper
end

Tourest/app/views/users/finish_signup.html.erb
<div id="wrapper" style="margin-top:100px;">
    <div class="container">
      <div class="col-md-10 col-sm-10 col-xs-12 container">
        <div id="add-email" class="container">
        <h1>Add Email</h1>
        <%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f| %>
        <% if @show_errors && current_user.errors.any? %>
        <div id="error_explanation">
          <% current_user.errors.full_messages.each do |msg| %>
            <%= msg %><br>
          <% end %>
        </div>
        <% end %>
        <div class="form-group">
          <%= f.label :email %>
          <div class="controls">
            <%= f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Example: email@me.com' %>
            <p class="help-block">Please confirm your email address. No spam.</p>
          </div>
        </div>
        <div class="actions">
          <%= f.submit 'Continue', :class => 'btn btn-primary' %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

Tourest/app/views/users/show.html.erb
<% provide(:title, "Profile Page") %>

<div id="wrapper" style="margin-top:100px;">
	<h2><%= @user.name %></h2>

	<%= link_to "Setting", edit_user_registration_path(current_user), :class => 'btn btn-primary' %>
</div>